theme: jekyll-theme-cayman
title: OpenWrt for RPi
description: A plug-and-play OpenWrt build for the Raspberry Pi
show_downloads: true
github:
  zip_url: https://github.com/damianperera/openwrt-rpi/releases/latest/download/openwrt.img.gz
  tar_url: https://github.com/damianperera/openwrt-rpi/releases/latest/download/openwrt.img.gz
