name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync and Build
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Pull changes from wulfy23's repo
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: wulfy23/rpi4
        upstream_branch: master
        target_branch: wulfy23/rpi4
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication
    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "Starting build"
      else: echo "No new commits, skipping build"
# jobs:
#   update:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Checkout branch main
#        uses: actions/checkout@v1
#        with:
#         fetch-depth: 0
#         ref: 'main'
#      - name: Checkout wulfy23's rpi4 repo
#        uses: actions/checkout@v1
#        with:
#         repository: wulfy23/rpi4
#         fetch-depth: 0
#         ref: 'master'
#         clean: false
#      - name: Commit changes
#        run: |
#         git config --local user.email "bot@perera.io"
#         git config --local user.name "Github Actions"
#         git add .
#         git commit -m "Updated data"
#      - name: Push to prod
#        uses: ad-m/github-push-action@master
#        with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: tests
#         force: true
