name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync and Build
    steps:
    - name: Checkout damianperera/openwrt-rpi
      uses: actions/checkout@v2
    - name: Checkout wulfy23/rpi4
      uses: actions/checkout@v2
      with:
        repository: wulfy23/rpi4
        path: wulfy
    - name: List
      run: ls -l
    - name: Mount RPi image
      run: |
       sudo su
       apt-get install -y kpartx gunzip
       cd wulfy/builds/devel
       cd "$(ls -t1 -d rpi-4_*/ | head -n1)"
       gunzip -v *.img.gz
       kpartx -a *.img
       mount -o rw -t ext4 /dev/mapper/loop0p2 /mnt/rpi4
      
# jobs:
#   update:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Checkout branch main
#        uses: actions/checkout@v1
#        with:
#         fetch-depth: 0
#         ref: 'main'
#      - name: Checkout wulfy23's rpi4 repo
#        uses: actions/checkout@v1
#        with:
#         repository: wulfy23/rpi4
#         fetch-depth: 0
#         ref: 'master'
#         clean: false
#      - name: Commit changes
#        run: |
#         git config --local user.email "bot@perera.io"
#         git config --local user.name "Github Actions"
#         git add .
#         git commit -m "Updated data"
#      - name: Push to prod
#        uses: ad-m/github-push-action@master
#        with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: tests
#         force: true
