name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync and Build
    steps:
    - name: Checkout damianperera/openwrt-rpi
      uses: actions/checkout@v2
    - name: Checkout wulfy23/rpi4
      uses: actions/checkout@v2
      with:
        repository: wulfy23/rpi4
        path: wulfy
#     - name: Checkout alexchamberlain/piimg
#       uses: actions/checkout@v2
#       with:
#         repository: alexchamberlain/piimg
#         path: piimg
#     - name: Install piimg
#       run: |
#        sudo apt-get install -y libudev1 libudev-dev libparted-dev
#        cd piimg
#        sudo make install
#        cd ../
#     - name: Mount RPi image
#       run: |
#        cd wulfy/builds/devel
#        cd "$(ls -t1 -d rpi-4_*/ | head -n1)"
#        gunzip -v *.img.gz || echo 0
#        mv *.img rpi.img
#        sudo mkdir -p /mnt/rpi4
#        sudo piimg mount rpi.img /mnt/rpi4
    - name: Mount RPi image
      run: |
       cd wulfy/builds/devel
       cd "$(ls -t1 -d rpi-4_*/ | head -n1)"
       gunzip -v *.img.gz || echo 0
       mv *.img rpi.img
       kpartx="$(sudo kpartx -avs rpi.img)"
       sudo kpartx -avs rpi.img
       read img_boot_dev img_root_dev <<<$(grep -o 'loop.p.' <<<"$kpartx")
       sleep 0.5
       echo img_boot_dev: $img_boot_dev img_root_dev: $img_root_dev
       img_boot_dev=/dev/mapper/$img_boot_dev
       img_root_dev=/dev/mapper/$img_root_dev
       sudo mkdir -p /mnt/rpi4
       sudo mount -t ext4 $img_root_dev /mnt/rpi4 || die "Could not mount $img_root_dev /mnt/rpi4"
       sudo mkdir -p /mnt/rpi4/boot || die "Could not mkdir /mnt/rpi4/boot"
       sudo mount -t vfat $img_boot_dev /mnt/rpi4/boot || die "Could not mount $img_boot_dev /mnt/rpi4/boot"
       cp -a "$(type -p qemu-arm-static)" /mnt/rpi4/usr/bin/ || die "Could not copy qemu-arm-static"
       echo "Raspbian Image Details:"
       df -h /mnt/rpi4/boot mnt/rpi4 | sed -e "s#$(pwd)/##"
      
# jobs:
#   update:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Checkout branch main
#        uses: actions/checkout@v1
#        with:
#         fetch-depth: 0
#         ref: 'main'
#      - name: Checkout wulfy23's rpi4 repo
#        uses: actions/checkout@v1
#        with:
#         repository: wulfy23/rpi4
#         fetch-depth: 0
#         ref: 'master'
#         clean: false
#      - name: Commit changes
#        run: |
#         git config --local user.email "bot@perera.io"
#         git config --local user.name "Github Actions"
#         git add .
#         git commit -m "Updated data"
#      - name: Push to prod
#        uses: ad-m/github-push-action@master
#        with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: tests
#         force: true
