name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync and Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: wulfy23/rpi4
        path: wulfy
    - name: List
      run: ls -l
# jobs:
#   update:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Checkout branch main
#        uses: actions/checkout@v1
#        with:
#         fetch-depth: 0
#         ref: 'main'
#      - name: Checkout wulfy23's rpi4 repo
#        uses: actions/checkout@v1
#        with:
#         repository: wulfy23/rpi4
#         fetch-depth: 0
#         ref: 'master'
#         clean: false
#      - name: Commit changes
#        run: |
#         git config --local user.email "bot@perera.io"
#         git config --local user.name "Github Actions"
#         git add .
#         git commit -m "Updated data"
#      - name: Push to prod
#        uses: ad-m/github-push-action@master
#        with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: tests
#         force: true
